#!/usr/bin/env python3
"""
ui-kit — token/DNA-driven UI component library for a brand repository.

usage:  python3 build.py --repo /abs/path/BRAND-REPO [--no-shots] [--audit]

Writes (all idempotent, owned by this module):
  SOURCE/CSS/<p>-ui.css                      components (recipe + core + shape layer + motion/motif flavour)
  SOURCE/JS/<p>-ui.js                        accessible behaviours (classic script, no deps)
  SOURCE/JSON/ui-kit.json                    recipe summary + component inventory (for website / brand-book modules)
  UI-DESIGN-SYSTEM/components/index.html     gallery + documentation (gallery.css next to it)
  UI-DESIGN-SYSTEM/components/previews/*.png overview + section crops, light / dark / contrast / mobile
  UI-DESIGN-SYSTEM/components/contrast-report.json
  UI-DESIGN-SYSTEM/react/<Brand>UI.jsx       minimal React wrappers (Button, Card, Input, Tag, Alert)
  UI-DESIGN-SYSTEM/README.md, components/README.md, tokens/README.md (if missing)
"""
import argparse, json, os, re, shutil, subprocess, sys, time
sys.dont_write_bytecode = True          # keep the module folder free of __pycache__
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..', '..', '..', 'scripts'))
sys.path.insert(0, os.path.join(HERE, 'lib'))
import forge_lib as F          # noqa: E402
import recipe as RC            # noqa: E402
import flavour as FL           # noqa: E402
from icons import icons as fallback_icons, ALIASES   # noqa: E402
from gallery import Gallery    # noqa: E402

TPL = os.path.join(HERE, 'templates')
PLATED = ['btn', 'chip', 'card', 'alert', 'toast', 'modal__frame', 'menu__panel', 'popover', 'tooltip', 'pagination__link',
          'pricing__plan', 'testimonial', 'empty', 'error-summary', 'accordion__icon', 'surface']
COMPONENTS = {
    'Actions': ['btn (--primary --secondary --ghost --link --destructive --inverse · --sm --lg --icon --block · loading/disabled)', 'btn-group'],
    'Forms': ['form', 'form__row', 'field (+__label __hint __req __opt __count)', 'input', 'textarea', 'select', 'search', 'input-group', 'check', 'radio',
              'choices / choice', 'switch', 'range', 'file', 'msg (--error --success --warning --info)', 'error-summary', 'fieldset'],
    'Content': ['tag', 'badge', 'chip', 'card (--media --stat --profile --offering --event --post --flat --outline --brand --horizontal)', 'accordion',
                'avatar / avatar-group', 'empty', 'divider (--label --motif)', 'kbd', 'code', 'snippet', 'blockquote', 'testimonial', 'pricing',
                'stats / stat', 'list (--check --divided, ol)', 'dl', 'ph (placeholder art)'],
    'Navigation': ['logo', 'header (--sticky --glass)', 'nav', 'menu (mobile drawer)', 'lang', 'tabs (--pills --boxed)', 'breadcrumbs', 'pagination', 'stepper', 'footer', 'segmented'],
    'Feedback': ['alert (--info --success --warning --error --outline)', 'banner (--brand)', 'toaster / toast', 'progress (--thin --indeterminate)', 'meter', 'spinner', 'skeleton'],
    'Overlays': ['modal (dialog)', 'drawer', 'tooltip', 'popover', 'term'],
    'Utilities': ['surface', 'scope', 'on-brand', 'sample', 'close', 'link'],
}


def sub(text, m):
    for k, v in m.items():
        text = text.replace('{{' + k + '}}', str(v))
    return text


def tpl(name):
    return open(os.path.join(TPL, name), encoding='utf-8').read()


def pascal(name):
    s = re.sub(r'[^0-9A-Za-z]+', ' ', name).title().replace(' ', '')
    return s if s and s[0].isalpha() else 'Brand' + s


def build_css(b, R):
    p = b.p
    plated = ', '.join(f'.{p}-{c}' for c in PLATED)
    tl = 'var(--_cut)' if R['facets'] else '0px'
    m = {'p': p, 'G': b.G, 'BRAND_NAME': b.name, 'PLATED': plated, 'ANGLE': f"{R['angle']:g}", 'TAN': f"{float(R['vars']['--ui-tan']):.3f}",
         'CORNERS': 'top-left + bottom-right (faceted)' if R['facets'] else 'bottom-right', 'TL': tl,
         'TAG_TL': 'var(--_k)' if R['facets'] else '0px', 'AV_TL': 'var(--_k)' if R['facets'] else '0px', 'CORNER': R['corner']}
    if R['corner'] == 'soft':
        ir = 'calc(var(--_r) - var(--ui-media-inset))'
        m['MEDIA_R'] = f'{ir} {ir} var(--radius-xl) {ir}' if R['family'] == 'organic' else ir
        m['MEDIA_R_H'] = f'{ir} {ir} {ir} var(--radius-xl)' if R['family'] == 'organic' else ir
    else:
        ir = 'calc(var(--_r) - var(--_bw))'
        m['MEDIA_R'] = f'{ir} {ir} 0 0'
        m['MEDIA_R_H'] = f'{ir} 0 0 {ir}'
    m['SEARCH_R'] = 'var(--radius-pill)' if R['corner'] == 'round' else 'var(--ui-r-control)'
    head = f"""/* ==========================================================================
   {b.name} — {p}-ui.css · UI component layer
   Generated by brand-system-forge / assets/modules/ui-kit from the design DNA:
     {RC.summary(R)}
   Load AFTER {p}-core.css (fonts + tokens + colours):
     <link rel="stylesheet" href="…/SOURCE/CSS/{p}-core.css">
     <link rel="stylesheet" href="…/SOURCE/CSS/{p}-ui.css">
     <script src="…/SOURCE/JS/{p}-icons.js"></script>  (optional)   <script src="…/SOURCE/JS/{p}-ui.js"></script>
   Gallery & docs: UI-DESIGN-SYSTEM/components/index.html
   Naming: .{p}-block · .{p}-block__element · .{p}-block--modifier · state in ARIA or .is-* ·
           .is-hover / .is-focus / .is-active are documentation snapshots only · --_x = private to a component.
   Every colour is a --color-* token; theme-dependent choices are re-declared per theme scope below.
   Regenerate: python3 build.py --repo <repo> (module folder) — hand edits are overwritten.
   ========================================================================== */
"""
    rec = '/* ---- RECIPE · theme-independent decisions (density, type voice, shape, motion) ---- */\n:root {\n' + RC.css_vars(R['vars']) + '\n}\n'
    rec += '@media (max-width: 767px) { :root { --ui-header-h: 64px; --ui-card-pad: var(--space-5); --ui-panel-pad: var(--space-6); } }\n'
    rec += '/* ---- RECIPE · per-theme colour choices (picked by measured WCAG contrast; see contrast-report.json) ---- */\n' + RC.theme_css(R)
    core = sub(tpl('ui-core.css'), m)
    shape = sub(tpl('shape-cut.css' if R['corner'] == 'cut' else 'shape-radius.css'), m)
    parts = [head, rec, core, shape, FL.motion(R, p), FL.family(R, p, b), FL.languages(R, p, b), FL.preferences(R, p, plated)]
    return '\n'.join(x for x in parts if x)


def build_js(b, R, ic):
    st = R['stroke']
    return sub(tpl('ui.js'), {'p': b.p, 'G': b.G, 'BRAND_NAME': b.name, 'ICONS_JSON': json.dumps(ic, ensure_ascii=False),
                              'ICON_ALIASES': json.dumps(ALIASES), 'STROKE_W': st.get('icon_px_at_24') or 1.75,
                              'STROKE_CAP': st.get('cap') or 'round', 'STROKE_JOIN': st.get('join') or 'round'})


def esc_md(s):
    return str(s).replace('<', '&lt;')


def shape_note(R):
    return {'cut': 'chamfers via a clip-path plate on `::before` (corners: ' + ('top-left + bottom-right' if R['facets'] else 'bottom-right') + '); hover wipes along the logo angle',
            'round': 'pill buttons, tags, chips and search; generous card radii; circular avatars and steps',
            'soft': 'large soft radii, inset media with an organic corner, no hard edges',
            'rounded': 'moderate radii from the radius tokens', 'square': 'crisp 0–2px corners'}[R['corner']]


def motion_note(R):
    return {'snap': 'short durations, no overshoot; press drops 1px, cards step onto a hard shadow',
            'slide': 'lateral moves of icons and indicators',
            'glide': 'smooth lift with growing depth; press settles with a slight scale',
            'flow': 'slow, springy toggles; surfaces float up a little'}[R['motion']]


def write_readmes(b, R, g, files, shots):
    p, G = b.p, b.G
    ui = b.path('UI-DESIGN-SYSTEM')
    comp_list = '\n'.join(f'- **{grp}** — ' + ', '.join(f'`.{p}-{c.split(" ")[0]}`' + (c[len(c.split(" ")[0]):] if ' ' in c else '') for c in items) for grp, items in COMPONENTS.items())
    sample = '\n> **Sample content.** Labels and texts in the gallery come from `SOURCE/CONFIG/content.json`, which is still placeholder content.\n' if g.sample else ''
    react = os.path.relpath(files['react'], ui)
    icons_state = (f'`SOURCE/JS/{p}-icons.js` → `{G}.icon(name, {{size, label}})` (found)' if os.path.exists(b.path('SOURCE', 'JS', f'{p}-icons.js'))
                   else f'`SOURCE/JS/{p}-icons.js` (not built yet — the kit uses its built-in fallback icons; rebuild after the icons module)')
    readme = f"""# {b.name} — UI design system

Token- and DNA-driven component library: **{RC.summary(R)}**.
Open **[components/index.html](components/index.html)** (works offline from the folder) for the live gallery, states, code and themes.
{sample}
## Files

| What | Where |
|---|---|
| Design tokens (CSS, DTCG JSON, Tailwind preset) | `tokens/` (mirrors `SOURCE/CSS/tokens.css`, `colors.css`, `SOURCE/JSON/design-tokens.json`) |
| Foundation CSS (fonts, tokens, base, type, layout, shape utilities) | `SOURCE/CSS/{p}-core.css` |
| **Component CSS** | `SOURCE/CSS/{p}-ui.css` |
| **Behaviours (JS)** | `SOURCE/JS/{p}-ui.js` — classic script, no dependencies |
| Icons (optional) | {icons_state} |
| Gallery & docs | `components/index.html` (+ `gallery.css`), previews in `components/previews/` |
| Contrast report | `components/contrast-report.json` — every button / control state per theme |
| React wrappers | `{react}` — Button, Card, Input, Tag, Alert (plain JSX, no build step required by the kit) |
| Machine-readable summary | `SOURCE/JSON/ui-kit.json` |

## Use

```html
<link rel="stylesheet" href="SOURCE/CSS/{p}-core.css">
<link rel="stylesheet" href="SOURCE/CSS/{p}-ui.css">
…
<button class="{p}-btn {p}-btn--primary">{esc_md(b.labels.get('cta_primary') or 'Get started')}</button>
<script src="SOURCE/JS/{p}-icons.js"></script>   <!-- optional -->
<script src="SOURCE/JS/{p}-ui.js"></script>
```

Behaviours initialise on `DOMContentLoaded` from data attributes (`data-{p}-tabs`, `data-{p}-accordion`, `data-{p}-modal-open`, `data-{p}-menu-toggle`,
`data-{p}-tooltip`, `data-{p}-popover`, `data-{p}-dismiss`, `data-{p}-toast`, `form[data-{p}-validate]`, `table[data-{p}-sort]`, `data-{p}-theme-switch` …).
After inserting markup call `{G}.ui.init(container)`. API: `{G}.ui.toast({{title, text, tone}})`, `{G}.ui.modal.open(id)`, `{G}.ui.theme.set('dark')`.

## Components

{comp_list}

## How the design DNA shapes the kit

| DNA | Value | Effect |
|---|---|---|
| `corner.style` | `{R['corner']}`{f" · {R['angle']:g}°" if R['corner'] == 'cut' else ''} | {shape_note(R)} |
| `shadow_style` | `{R['shadow']}` | elevation tokens → `--ui-elev-0…3` ({'drop-shadow() filters that follow the chamfer' if R['corner'] == 'cut' else 'box-shadows'}) |
| `motion.character` | `{R['motion']}` (energy {R['energy']:.2f}) | {motion_note(R)} |
| `density` | `{R['density']}` | control heights {R['vars']['--ui-h-sm']} / {R['vars']['--ui-h-md']} / {R['vars']['--ui-h-lg']}, card padding `{R['vars']['--ui-card-pad']}` |
| `type_voice.display_case` | `{R['case']}` | {'buttons and titles set in the display face, in capitals' if R['case'] == 'upper' else 'titles in the display face, buttons in the sans'} |
| `motifs` / `patterns` | {', '.join(R['motifs'][:4])} | {R['family']} family: indicators, list markers, dividers, spinners, placeholder art |

## Theming

Three themes from the same tokens: light (default), dark and high-contrast — `<html data-theme="dark|contrast">`, or none to follow the OS
(`prefers-color-scheme`, `prefers-contrast`). Any element can carry `data-theme` (add `.{p}-scope` to paint its ground). The gallery's switch
persists the choice in `localStorage` (`{p}-theme`, wrapped in try/catch). Colour choices that depend on contrast (button text per state,
indicator line, checked-control fill, field border) are computed per theme at build time and written as references to `--color-*` tokens.

## Accessibility

- WAI-ARIA Authoring Practices keyboard maps for tabs, accordion, menu, dialogs; focus trap + Esc + focus return on every overlay.
- Visible 2px focus ring everywhere (`--color-focus`); cut shapes paint on `::before` so outlines are never clipped.
- Button/control text ≥ 4.5:1 in every state and theme, control borders ≥ 3:1 (`components/contrast-report.json`).
- Targets ≥ 44px; status never by colour alone; `prefers-reduced-motion` and `forced-colors` handled; `lang` on every other-language text.

## Regenerate

`python3 assets/modules/ui-kit/build.py --repo <this repo>` (from the brand-system-forge skill). Outputs are overwritten — customise by
adding a stylesheet after `{p}-ui.css`, or change the DNA / tokens and rebuild.
"""
    F.write(os.path.join(ui, 'README.md'), readme)
    comp = f"""# components/

- `index.html` — gallery + documentation of every component (live examples, states, code, theme switch). Open it directly from disk.
- `gallery.css` — documentation layout only (not part of the kit).
- `contrast-report.json` — measured contrast of every button / control state in the light, dark and contrast themes.
- `previews/` — PNG renders: {', '.join(sorted(shots)) or '(run without --no-shots)'}.

Regenerate with the `ui-kit` module (`build.py --repo …`). Do not edit by hand.
"""
    F.write(os.path.join(ui, 'components', 'README.md'), comp)
    tok = os.path.join(ui, 'tokens', 'README.md')
    if not os.path.exists(tok) and os.path.isdir(os.path.dirname(tok)):
        F.write(tok, f"""# tokens/

Design tokens of {b.name}, generated by the foundation (`scripts/build_tokens.py`) — mirrors of the files in `SOURCE/`.

| File | Use |
|---|---|
| `tokens.css` | CSS custom properties: type (`--type-*`), space, radius / cut, borders, shadows, motion, z-index, grid |
| `colors.css` | palette (`--{p}-*`), ramps and theme colours (`--color-*` for light / dark / contrast via `[data-theme]`) |
| `design-tokens.json` | DTCG JSON for design tools / Style Dictionary |
| `tailwind.preset.js` | Tailwind preset mapping the same tokens |

The UI kit (`SOURCE/CSS/{p}-ui.css`) only consumes these tokens; change a token and rebuild the kit to propagate it.
""")


def react_file(b, R):
    p, name = b.p, pascal(b.name)
    return f"""/* {b.name} — minimal React wrappers for {p}-ui.css (no build step needed by the kit; any JSX toolchain works).
   Load SOURCE/CSS/{p}-core.css + SOURCE/CSS/{p}-ui.css on the page. For behaviours (tabs, modals…) also load SOURCE/JS/{p}-ui.js
   and call window.{b.G}.ui.init(node) in an effect after rendering composite widgets. */
import React from 'react';

const cx = (...a) => a.filter(Boolean).join(' ');
const P = '{p}';

export function Button({{ variant = 'primary', size, icon, block, loading, as: Tag = 'button', className, children, ...rest }}) {{
  const props = Tag === 'button' ? {{ type: 'button', ...rest }} : rest;
  return (
    <Tag className={{cx(`${{P}}-btn`, `${{P}}-btn--${{variant}}`, size && `${{P}}-btn--${{size}}`, icon && `${{P}}-btn--icon`, block && `${{P}}-btn--block`, className)}}
      aria-busy={{loading || undefined}} {{...props}}>
      {{loading ? <span>{{children}}</span> : children}}
    </Tag>
  );
}}

export function Card({{ variant, title, href, meta, media, children, footer, className, ...rest }}) {{
  return (
    <article className={{cx(`${{P}}-card`, variant && `${{P}}-card--${{variant}}`, className)}} {{...rest}}>
      {{media && <div className={{`${{P}}-card__media`}}>{{media}}</div>}}
      <div className={{`${{P}}-card__body`}}>
        {{meta && <div className={{`${{P}}-card__meta`}}>{{meta}}</div>}}
        {{title && <h3 className={{`${{P}}-card__title`}}>{{href ? <a className={{`${{P}}-card__link`}} href={{href}}>{{title}}</a> : title}}</h3>}}
        {{children && <div className={{`${{P}}-card__text`}}>{{children}}</div>}}
      </div>
      {{footer && <div className={{`${{P}}-card__footer`}}>{{footer}}</div>}}
    </article>
  );
}}

export function Input({{ id, label, hint, error, required, as = 'input', className, ...rest }}) {{
  const auto = React.useId ? React.useId() : 'f';
  const fid = id || `${{P}}-${{auto}}`;
  const describedBy = [hint && `${{fid}}-hint`, error && `${{fid}}-msg`].filter(Boolean).join(' ') || undefined;
  const Control = as === 'textarea' ? 'textarea' : 'input';
  return (
    <div className={{cx(`${{P}}-field`, className)}}>
      <label className={{`${{P}}-field__label`}} htmlFor={{fid}}>{{label}}{{required && <span className={{`${{P}}-field__req`}}> Required</span>}}</label>
      {{hint && <p className={{`${{P}}-field__hint`}} id={{`${{fid}}-hint`}}>{{hint}}</p>}}
      <Control id={{fid}} className={{as === 'textarea' ? `${{P}}-textarea` : `${{P}}-input`}} required={{required}} aria-invalid={{error ? 'true' : undefined}} aria-describedby={{describedBy}} {{...rest}} />
      {{error && <p className={{`${{P}}-msg ${{P}}-msg--error`}} id={{`${{fid}}-msg`}}><span className="sr-only">Error: </span>{{error}}</p>}}
    </div>
  );
}}

export function Tag({{ variant, className, children, ...rest }}) {{
  return <span className={{cx(`${{P}}-tag`, variant && `${{P}}-tag--${{variant}}`, className)}} {{...rest}}>{{children}}</span>;
}}

export function Alert({{ tone = 'info', title, children, onDismiss, className, ...rest }}) {{
  return (
    <div className={{cx(`${{P}}-alert`, `${{P}}-alert--${{tone}}`, className)}} role={{tone === 'error' ? 'alert' : 'status'}} {{...rest}}>
      <span className={{`${{P}}-alert__icon`}} aria-hidden="true" data-{p}-icon={{{{ info: 'info', success: 'check', warning: 'warning', error: 'error' }}[tone]}} />
      <div className={{`${{P}}-alert__body`}}>
        {{title && <p className={{`${{P}}-alert__title`}}>{{title}}</p>}}
        {{children && <p className={{`${{P}}-alert__text`}}>{{children}}</p>}}
      </div>
      {{onDismiss && <button type="button" className={{`${{P}}-close`}} aria-label="Dismiss" onClick={{onDismiss}}>×</button>}}
    </div>
  );
}}

const {name}UI = {{ Button, Card, Input, Tag, Alert }};
export default {name}UI;
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--repo', required=True)
    ap.add_argument('--no-shots', action='store_true', help='skip PNG previews')
    ap.add_argument('--audit', action='store_true', help='render every theme and report rendered text contrast below AA (needs Playwright)')
    a = ap.parse_args()
    t0 = time.time()
    b = F.load(a.repo)
    p = b.p
    R = RC.build(b)
    ic = fallback_icons(R)

    files = {'css': b.path('SOURCE', 'CSS', f'{p}-ui.css'), 'js': b.path('SOURCE', 'JS', f'{p}-ui.js'),
             'json': b.path('SOURCE', 'JSON', 'ui-kit.json'), 'react': b.path('UI-DESIGN-SYSTEM', 'react', f'{pascal(b.name)}UI.jsx')}
    F.write(files['css'], build_css(b, R))
    F.write(files['js'], build_js(b, R, ic))

    at = 'UI-DESIGN-SYSTEM/components'
    comp_dir = b.path(at)
    os.makedirs(comp_dir, exist_ok=True)
    F.write(os.path.join(comp_dir, 'gallery.css'), sub(tpl('gallery.css'), {'p': p, 'BRAND_NAME': b.name}))
    g = Gallery(b, R, ic, at)
    body = g.build()
    head = (f'<link rel="stylesheet" href="{b.rel(at, f"SOURCE/CSS/{p}-ui.css")}"><link rel="stylesheet" href="gallery.css">'
            f'<meta name="description" content="{F.esc(b.name)} UI kit — components, states and themes">'
            '<script>(function(){try{if(/[?&]preview/.test(location.search))document.documentElement.classList.add("is-preview")}catch(e){}})()</script>')
    scripts = ('mark-data.js', 'wordmark-data.js', 'dna-data.js', 'content-data.js', '{p}-mark.js', '{p}-icons.js', '{p}-ui.js')
    html = F.page(b, 'UI kit', body, at, head=head, scripts=scripts)
    F.write(os.path.join(comp_dir, 'index.html'), html)
    rep = {'brand': b.name, 'generated_by': 'ui-kit', 'note': 'WCAG 2.x contrast of component colour choices per theme (text ≥ 4.5, non-text ≥ 3).',
           'themes': R['report']}
    F.write(os.path.join(comp_dir, 'contrast-report.json'), json.dumps(rep, indent=1, ensure_ascii=False))
    F.write(files['react'], react_file(b, R))
    inv = {'module': 'ui-kit', 'version': json.load(open(os.path.join(HERE, 'module.json')))['version'], 'prefix': p, 'global': b.G,
           'css': f'SOURCE/CSS/{p}-ui.css', 'js': f'SOURCE/JS/{p}-ui.js', 'gallery': f'{at}/index.html',
           'recipe': {k: R[k] for k in ('corner', 'angle', 'facets', 'density', 'motion', 'energy', 'case', 'shadow', 'crop', 'family')},
           'summary': RC.summary(R), 'components': {grp: [f'{p}-' + c.split(' ')[0] for c in items] for grp, items in COMPONENTS.items()},
           'behaviours': ['theme-switch', 'theme-toggle', 'header', 'menu-toggle', 'tabs', 'accordion', 'modal-open', 'tooltip', 'popover', 'dismiss', 'toast',
                          'validate', 'count', 'sort', 'file', 'range', 'search', 'copy'],
           'icons': 'SOURCE/JS/%s-icons.js' % p if os.path.exists(b.path('SOURCE', 'JS', f'{p}-icons.js')) else 'built-in fallback'}
    F.write(files['json'], json.dumps(inv, indent=1, ensure_ascii=False))

    shots = []
    if not a.no_shots:
        prev = os.path.join(comp_dir, 'previews')
        if os.path.isdir(prev):
            shutil.rmtree(prev)
        os.makedirs(prev, exist_ok=True)
        url = 'file://' + os.path.join(comp_dir, 'index.html')
        jobs = []
        for th in ('light', 'dark', 'contrast'):
            jobs.append({'in': f'{url}?preview&theme={th}', 'out': os.path.join(prev, f'overview-{th}.png'), 'w': 1440, 'h': 960, 'wait': 350})
        jobs.append({'in': f'{url}?preview&theme=light', 'out': os.path.join(prev, 'overview-mobile.png'), 'w': 390, 'h': 844, 'scale': 2, 'wait': 350})
        for sid in ('buttons', 'forms', 'cards', 'navigation', 'feedback', 'overlays', 'data', 'identity'):
            for th in ('light', 'dark'):
                jobs.append({'in': f'{url}?preview&theme={th}', 'out': os.path.join(prev, f'{sid}-{th}.png'), 'w': 1440, 'h': 1000, 'selector': f'#{sid}', 'wait': 300})
        F.shots(jobs)
        shots = [os.path.basename(j['out']) for j in jobs if os.path.exists(j['out'])]
        opt = os.path.join(HERE, '..', '..', '..', 'scripts', 'optimize_png.js')
        if shutil.which('node') and os.path.exists(opt):
            subprocess.run(['node', opt, prev], capture_output=True, timeout=300)
    write_readmes(b, R, g, files, shots)

    if a.audit:
        subprocess.run(['node', os.path.join(HERE, 'lib', 'audit.js'), os.path.join(comp_dir, 'index.html')], timeout=600)

    kb = os.path.getsize(files['css']) // 1024
    print(f"ui-kit: {p}-ui.css {kb} KB · {p}-ui.js · gallery {g.n_examples} examples · {len(shots)} previews · "
          f"{R['corner']}/{R['shadow']}/{R['motion']}/{R['density']} · {time.time() - t0:.0f}s")


if __name__ == '__main__':
    main()
