"""docs.py — LOGO/README.md and the small READMEs of every output folder (numbers come from the built data)."""
import os
import forge_lib as F
from svgkit import contrast

MARK = '<!-- generated by the logo-system module — rerun it instead of editing by hand -->'
VNAME = {'color': 'Full colour', 'on-dark': 'On dark', 'foundation': 'One colour — foundation', 'white': 'One colour — white', 'primary': 'One colour — primary'}


def _count(c, folder, ext=None):
    d = c.b.path('LOGO', folder)
    if not os.path.isdir(d): return 0
    return len([f for f in os.listdir(d) if not f.startswith(('.', '_')) and (ext is None or f.endswith(ext)) and f != 'README.md'])


def _f(path):
    return path.split('LOGO/', 1)[1] if 'LOGO/' in path else path


def write_readmes(c, data):
    b, ink = c.b, c.ink
    s, p = c.slug, c.primary
    lt = b.logo_type
    files = c.files
    kind = {'combination': 'a **combination logo** — symbol + traced lettering in a fixed arrangement',
            'wordmark': 'a **wordmark** — the traced lettering is the logo; a monogram in the brand container covers small spaces',
            'emblem': 'an **emblem** — one closed unit with its lettering inside; the typeset name accompanies it in lockups',
            'symbol': 'a **symbol** — the mark stands alone; the typeset name sits beside or below it in lockups'}.get(lt, lt)
    on_p = ink.on_primary_variant
    L = []
    L += [MARK, f'# {b.name} — Logo', '',
          f'The {b.name} logo is {kind}. Every file here is generated from the foundations (`LOGO/SVG/`, `SOURCE/JSON/logo-parts.json`, '
          '`SOURCE/JS/wordmark-data.js`) — nothing is redrawn and the lettering is never re-typeset.', '',
          '![Logo sheet](logo-sheet.png)', '',
          '> **Quick pick**', f'> - Light ground → `{_f(files[p]["color"]["svg"])}`',
          f'> - Dark ground → `{_f(files[p]["on-dark"]["svg"])}`',
          f'> - Primary-colour field → `{_f(files[p][on_p]["svg"])}`',
          f'> - Wide, shallow space → `{_f(files[c.wide]["color"]["svg"])}` · square or tall → `{_f(files[c.square]["color"]["svg"])}`',
          f'> - Avatars → `AVATARS/` · website icons → `FAVICON/` (+ `FAVICON/head-snippet.html`)', '']
    # ---- files
    L += ['## 1. Folders', '', '| Folder | What is inside | Files |', '|---|---|---|',
          f'| `SVG/` | Foundation drawings: original rebuild (`logo-original*`), symbol variants, compact mark. Made by the foundation scripts. | {_count(c, "SVG")} |',
          f'| `PNG/` | The **original artwork** (never altered) + large transparent exports of every lockup (512 / 1024 / 2048 px wide) and square symbol PNGs 16–1024 px. | {_count(c, "PNG")} |',
          f'| `LOCKUPS/` | Every lockup in full colour (light grounds) and on-dark — SVG master + PNG @1x / @2x, transparent. | {_count(c, "LOCKUPS")} |',
          f'| `MONOCHROME/` | The same lockups in one colour: foundation, white{", primary" if ink.primary_ok else ""} — SVG + PNG @1x / @2x. | {_count(c, "MONOCHROME")} |',
          f'| `GUIDES/` | Clear space, minimum sizes (real pixels), construction (grid, optical centre, proportions) and misuse — HTML + PNG. | {_count(c, "GUIDES")} |',
          f'| `FAVICON/` | `favicon.ico` (16/32/48), `favicon-16/32/48.png`, `apple-touch-icon.png`, `android-chrome-192/512.png`, `maskable-192/512.png`, `icon.svg`, `site.webmanifest`, `head-snippet.html`, SVG masters. | {_count(c, "FAVICON")} |',
          f'| `AVATARS/` | Profile images 400 and 1080 px in {len(c.avatars)} colourways, circle-safe. | {_count(c, "AVATARS")} |',
          '| `logo-sheet.html` / `.png` | One-page overview of the whole system. | 2 |', '']
    # ---- lockups
    L += ['## 2. Lockups', '', f'File names: `{s}-<lockup>-<colourway>.svg` (+ `.png` @1x, `@2x.png`). Colourways: '
          + ', '.join(f'`{v}`' for v in ink.variants()) + '.', '',
          '| Lockup | Use | Aspect | Minimum | Clear space |', '|---|---|---|---|---|']
    for l in c.lockups:
        m = c.mins[l.name]
        mm = f'{m["px"]} px {"wide" if m["measure"] == "width" else "tall"} · {m["mm"]} mm'
        cs = '1X' if l.kind not in ('symbol', 'compact') else f'{c.rules["clear_pct"]}% of the shorter side'
        L.append(f'| **{l.title}** `{l.name}` | {l.use} | {l.aspect:.2f} : 1 | {mm} | {cs} |')
    L += ['', f'**Primary lockup:** `{p}`. ' + {
        'combination': 'It is the original arrangement, rebuilt in vector. The alternates keep the measured symbol-to-lettering scale and gap.',
        'wordmark': 'The lettering itself. The compact mark is for avatars, app icons and favicons only — never next to the wordmark.',
        'emblem': 'Emblem beside the typeset name. The emblem alone is the original artwork and stays one unit.',
        'symbol': 'Symbol beside the typeset name. The symbol alone works where the name is already present.'}.get(lt, ''), '']
    # ---- construction
    L += ['## 3. Construction', '', '**X = cap height of the ' + ('lettering' if lt in ('combination', 'wordmark') else 'name') +
          '** = 100 units in every lockup file. Text aligns to the mark\'s **optical centre** '
          f'({", ".join(f"{v:.3f}" for v in ((b.mark or {}).get("optical_center") or [0.5, 0.5]))} of the mark box), not its bounding box.', '',
          '| Lockup | Mark height | Gap | Lettering / name | Notes |', '|---|---|---|---|---|']
    for l in c.lockups:
        n = l.notes
        extra = []
        if 'lines' in n and n['lines'] > 1: extra.append(f'{n["lines"]} lines, advance {n.get("line_advance", 1.2):.2f}X')
        if 'descriptor_cap' in n: extra.append(f'descriptor cap {n["descriptor_cap"]:.2f}X, {n.get("descriptor_gap", 0):.2f}X below')
        if 'arrangement' in n: extra.append(n['arrangement'])
        if 'lang' in n: extra.append(f'local name ({n["lang"]})')
        L.append(f'| {l.title} | {(str(round(n["mark_h"], 2)) + "X") if "mark_h" in n else "—"} | {(str(round(n["gap"], 2)) + "X") if "gap" in n else "—"} | '
                 f'{(str(round(n["lettering_h"], 2)) + "X tall") if "lettering_h" in n else ("cap 1X" if l.kind == "lockup" else "—")} | {"; ".join(extra) or "—"} |')
    if c.compact_lockup is not None:
        L += ['', f'Compact mark container: **{c.compact_lockup.shape_name}** (from `design-dna.json → corner.style`). One-colour versions knock the monogram out of the container.']
    L += ['', '![Construction](GUIDES/construction.png)', '']
    # ---- clear space + min sizes
    L += ['## 4. Clear space', '', f'- Lockups: **1X on every side**, measured from the logo box (mark box and the cap line / baseline of the text).',
          f'- Mark alone: **{c.rules["clear_pct"]}% of its shorter side**. Avatars, app icons and favicons carry their own padding.',
          '- Nothing enters the clear space: other logos, text, frame edges, busy image detail. Partner lockups sit 2X apart with a hairline between.', '',
          '![Clear space](GUIDES/clear-space.png)', '',
          '## 5. Minimum sizes', '',
          (f'- Compact mark: down to **{c.rules["compact_px"]} px / {c.rules["compact_mm"]} mm**; below the lockup minimum use it instead of the wordmark.' if lt == 'wordmark' else
           f'- Mark: master drawing from **{c.rules["master_px"]} px / {c.rules["master_mm"]} mm**; simplified drawing below that, down to **{c.rules["compact_px"]} px / {c.rules["compact_mm"]} mm**.'),
          f'- Lockups: never under **{c.rules["lockup_px"]} px / {c.rules["lockup_mm"]} mm** wide; each lockup\'s own minimum (table in §2) keeps the cap height ≥ 6 px and secondary lines ≥ 4 px.',
          '- Below a lockup\'s minimum, switch to a more compact lockup — never shrink past it.', '', '![Minimum sizes](GUIDES/minimum-sizes.png)', '']
    # ---- colour
    name_col = ink.F
    L += ['## 6. Colour and backgrounds', '', '| Ground | Use | Text contrast |', '|---|---|---|',
          f'| Light `{ink.light}` (and white, pale photos) | `color` | {contrast(name_col, ink.light):.1f} : 1 (foundation lettering) |',
          f'| Dark `{ink.dark}` (and dark photos) | `on-dark` — dark lettering turns paper `{ink.PA}` | {contrast(ink.PA, ink.dark):.1f} : 1 |',
          f'| Primary `{ink.P}` | one colour `{on_p}` | {contrast(ink.on_primary, ink.P):.1f} : 1 |']
    if ink.primary_ok:
        L.append(f'| Light, single spot colour | one colour `primary` `{ink.P}` | {contrast(ink.P, ink.PA):.1f} : 1 |')
    else:
        L.append(f'| — | no one-colour primary version: `{ink.P}` reaches only {contrast(ink.P, ink.PA):.1f} : 1 on paper (needs 3 : 1) | |')
    L += ['', 'Photos: place the logo on a calm area, a solid panel or a scrim. Never recolour parts of the logo, never use the light-ground file on dark.', '']
    # ---- favicon
    snip = open(b.path('LOGO', 'FAVICON', 'head-snippet.html'), encoding='utf-8').read().strip()
    L += ['## 7. Favicons, app icons, avatars', '',
          f'- Favicons use the compact mark{" (simplified drawing)" if lt != "wordmark" else " in its container"}; `icon.svg` ' +
          ('switches to the on-dark colours when the browser UI is dark.' if lt != 'wordmark' else 'is the container + monogram.'),
          f'- App icons: brand ground `{c.icon.get("theme_bg")}`, mark optically centred; maskable icons keep the mark inside the 80% safe circle; '
          f'`android-chrome-*` use the brand container ({c.icon.get("shape")}).',
          f'- Manifest: name “{c.manifest["name"]}”, short name “{c.manifest["short_name"]}”, theme `{c.manifest["theme_color"]}`, background `{c.manifest["background_color"]}`.',
          '- Avatars: ' + ', '.join(f'`avatar-{a["name"]}` (`{a["ground"]}`)' for a in c.avatars) + ' — the farthest point of the mark sits at 62% of the crop radius, so circular crops never cut it.', '',
          '```html', snip, '```', '']
    # ---- misuse
    L += ['## 8. Never', '', '![Misuse](GUIDES/misuse.png)', '',
          'Stretch · rotate · recolour · add effects · outline · place on busy backgrounds · use the light-ground file on dark · put the colour logo on the primary · '
          + ('re-typeset the lettering · break it into lines · re-space it' if lt == 'wordmark' else 're-typeset the lettering / name · rearrange the lockup · change its proportions')
          + ' · crowd the clear space.', '']
    L += ['## 9. Regenerate', '', '```bash', f'python3 <skill>/assets/modules/logo-system/build.py --repo {os.path.basename(b.repo)}', '```', '',
          'The module owns `LOCKUPS/`, `MONOCHROME/`, `GUIDES/`, `FAVICON/`, `AVATARS/`, the exports it lists in `SOURCE/JSON/logo-system.json`, '
          '`logo-sheet.*` and this README. It never touches `SVG/` or the original artwork. Other modules read `SOURCE/JSON/logo-system.json` '
          '(lockup files, recommended versions per ground, minimum sizes, clear space).', '']
    F.write(b.path('LOGO', 'README.md'), '\n'.join(L))

    sub = {
        'LOCKUPS': (f'Lockups — full colour and on-dark', [f'`{s}-<lockup>-color.svg` light grounds · `-on-dark.svg` dark grounds', 'Each SVG has a `.png` (@1x) and `@2x.png` (transparent).',
                    'X = cap height = 100 units; viewBoxes are tight to the artwork — clear space (1X) is documented, not baked in.']),
        'MONOCHROME': ('One-colour lockups', [f'`{s}-<lockup>-foundation|white{"|primary" if ink.primary_ok else ""}.svg` + PNG @1x/@2x.',
                       'Marks keep their knock-out lines (from `LOGO/SVG/symbol-black|white.svg`), so parts stay legible in one ink.',
                       'Use for single-ink print, stamps, embroidery, engraving, video supers and photos.']),
        'GUIDES': ('Logo guides', ['`clear-space` · `minimum-sizes` (rendered at real pixels) · `construction` · `misuse` — HTML (open in a browser) + PNG.',
                   'Files starting with `_` are helpers for the pages.']),
        'FAVICON': ('Favicons and app icons', ['Copy the folder to the site root and paste `head-snippet.html` into `<head>`.',
                    '`app-icon.svg`, `maskable.svg`, `app-icon-any.svg` are the editable masters of the PNGs.']),
        'AVATARS': ('Profile images', ['`avatar-<colourway>.svg` + `-400.png` / `-1080.png`. Circle-safe: upload the square, let the platform crop.']),
    }
    for folder, (title, lines) in sub.items():
        if os.path.isdir(b.path('LOGO', folder)):
            F.write(b.path('LOGO', folder, 'README.md'), '\n'.join([MARK, f'# {b.name} — {title}', ''] + [f'- {x}' for x in lines] +
                                                                  ['', 'Regenerate with the logo-system module; rules and file map in `../README.md`.', '']))
