#!/usr/bin/env python3
"""logo-system — the complete logo kit of a brand repository, built from its foundations.

    python3 build.py --repo /abs/path/to/BRAND-REPO [--svg-only] [--no-sheet]

Writes (inside the repo):
  LOGO/LOCKUPS/      lockups for the logo type — colour + on-dark — SVG + PNG @1x/@2x (transparent)
  LOGO/MONOCHROME/   the same lockups in one colour (foundation, white, primary when it holds 3:1) — SVG + PNG @1x/@2x
  LOGO/PNG/          large transparent exports (512/1024/2048 wide) + square symbol/compact PNGs (the original artwork is left alone)
  LOGO/GUIDES/       clear space, minimum sizes, construction (grid + optical centre), misuse — HTML + PNG
  LOGO/FAVICON/      favicon.ico (16/32/48), favicon-16/32/48.png, apple-touch-icon, android + maskable 192/512, icon.svg, site.webmanifest
  LOGO/AVATARS/      400 and 1080 px profile images in paper / primary / foundation colourways (circle-safe)
  LOGO/logo-sheet.html + .png, LOGO/README.md, SOURCE/JSON/logo-system.json (index for other modules)
"""
import argparse, json, math, os, re, shutil, sys, tempfile, time
sys.dont_write_bytecode = True
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, 'lib'))
sys.path.insert(0, os.path.join(HERE, '..', '..', '..', 'scripts'))
import forge_lib as F
from svgkit import (Item, Lockup, place_centre, contrast, f2, prefix_ids, recolor_all, colours, mix)
from logo import Ink, load_parts, build_lockups, container_path, corner_style, ContainerLockup, X
import pages, docs

OWNED = ['LOCKUPS', 'MONOCHROME', 'GUIDES', 'FAVICON', 'AVATARS']
VLABEL = {'color': 'full colour, light grounds', 'on-dark': 'dark grounds', 'foundation': 'one colour — foundation',
          'white': 'one colour — white', 'primary': 'one colour — primary'}
MIN_CAP_PX, MIN_SUB_CAP_PX = 6, 4          # smallest legible cap heights on screen (name / secondary line)
PX_PER_MM = 4                               # spec ratio (120 px ≈ 30 mm)


class Ctx:
    pass


def slugify(b):
    s = re.sub(r'[^a-z0-9]+', '-', (b.name or '').lower()).strip('-')
    return s or b.p


def spec_rules(b):
    r = {'clear_pct': 25, 'master_px': 48, 'master_mm': 12, 'compact_px': 16, 'compact_mm': 5, 'lockup_px': 120, 'lockup_mm': 30}
    p = b.path('SOURCE', 'CONFIG', 'production-spec.md')
    if os.path.exists(p):
        s = open(p, encoding='utf-8').read()
        m = re.search(r'Clear space\*\*\s*=\s*(\d+)\s*%', s)
        if m: r['clear_pct'] = int(m.group(1))
        m = re.search(r'master\s*≥\s*(\d+)\s*px\s*/\s*(\d+)\s*mm', s)
        if m: r['master_px'], r['master_mm'] = int(m.group(1)), int(m.group(2))
        m = re.search(r'compact\s*≥\s*(\d+)\s*px\s*/\s*(\d+)\s*mm', s)
        if m: r['compact_px'], r['compact_mm'] = int(m.group(1)), int(m.group(2))
        m = re.search(r'lockups\s*≥\s*(\d+)\s*px\s*/\s*(\d+)\s*mm', s)
        if m: r['lockup_px'], r['lockup_mm'] = int(m.group(1)), int(m.group(2))
    return r


def ceil_to(v, step): return int(math.ceil(v / step) * step)


def min_size(lk, rules):
    """minimum on-screen size of a lockup: {'measure': 'width'|'height', 'px', 'mm'}"""
    w, h = lk.size
    if lk.kind in ('symbol', 'compact'):
        return {'measure': 'height', 'px': rules['compact_px'], 'mm': rules['compact_mm'], 'master_px': rules['master_px']}
    need = [rules['lockup_px']]
    for it in lk.items:
        p = it.part
        if p.role in ('name', 'lettering'):
            cap = (p.cap or p.h) * it.s
            need.append(w * MIN_CAP_PX / cap)
        elif p.role in ('descriptor', 'local'):
            need.append(w * MIN_SUB_CAP_PX / (p.cap * it.s))
        elif p.role == 'symbol':
            need.append(w * rules['compact_px'] / (p.h * it.s))
    px = ceil_to(max(need), 10)
    return {'measure': 'width', 'px': px, 'mm': ceil_to(px / PX_PER_MM, 5)}


def px1(lk):
    """@1x PNG width"""
    a = lk.aspect
    if a >= 2.2: return 640
    if a >= 1.2: return 480
    return int(round(320 * a))


def job(c, src, out, w, h, transparent=True, wait=0, scale=1, full=False):
    c.jobs.append({'in': src, 'out': out, 'w': int(round(w)), 'h': int(round(h)), 'transparent': transparent, 'wait': wait,
                   'scale': scale, 'full': full})


def rel(c, p): return os.path.relpath(p, c.b.repo).replace(os.sep, '/')


# ------------------------------------------------------------------ lockups + monochrome + PNG exports
def build_lockup_files(c):
    b, ink = c.b, c.ink
    c.files = {}
    for lk in c.lockups:
        c.files[lk.name] = {}
        for v in ink.variants():
            folder = 'LOCKUPS' if v in ('color', 'on-dark') else 'MONOCHROME'
            name = f'{c.slug}-{lk.name}-{v}'
            title = f'{b.name} — {lk.title} ({VLABEL[v]})'
            desc = f'{lk.use} Generated by the logo-system module from the foundation SVGs; X = cap height = 100 units.'
            svg, vb = lk.svg(v, F.esc(title), F.esc(desc), pfx='a')
            p = b.path('LOGO', folder, name + '.svg')
            F.write(p, svg)
            w1 = px1(lk); h1 = w1 * vb[3] / vb[2]
            job(c, p, b.path('LOGO', folder, name + '.png'), w1, h1)
            job(c, p, b.path('LOGO', folder, name + '@2x.png'), 2 * w1, 2 * h1)
            entry = {'svg': rel(c, p), 'png': rel(c, p[:-4] + '.png'), 'png2x': rel(c, p[:-4] + '@2x.png')}
            if v in ('color', 'on-dark'):
                entry['exports'] = []
                for W in (512, 1024, 2048):
                    out = b.path('LOGO', 'PNG', f'{name}-{W}.png')
                    job(c, p, out, W, W * vb[3] / vb[2]); entry['exports'].append(rel(c, out)); c.png_written.append(out)
            c.files[lk.name][v] = entry
    # square symbol / compact PNGs (transparent). Below the master threshold the simplified drawing is used.
    sq = c.compact_lockup if b.logo_type == 'wordmark' else None
    for v in ('color', 'on-dark'):
        for size in (16, 32, 48, 64, 128, 256, 512, 1024):
            if sq is not None:
                src = square_svg(c, None, v, f'compact-{v}', lockup=sq)
                out = b.path('LOGO', 'PNG', f'{c.slug}-compact-{v}-{size}.png')
            else:
                part = c.parts['compact'] if size < c.rules['master_px'] else c.parts['mark']
                src = square_svg(c, part, v, f'{"compact" if size < c.rules["master_px"] else "symbol"}-{v}')
                out = b.path('LOGO', 'PNG', f'{c.slug}-symbol-{v}-{size}.png')
            job(c, src, out, size, size); c.png_written.append(out)


def square_svg(c, part, v, key, pad=0.0, lockup=None):
    """render-only square SVG (temp dir) of a part or a square lockup"""
    p = os.path.join(c.tmp, key + '.svg')
    if os.path.exists(p): return p
    if lockup is not None:
        svg, _ = lockup.svg(v, 'x', pfx='q')
    else:
        x0, y0, x1, y1 = part.box
        side = max(x1 - x0, y1 - y0) * (1 + 2 * pad)
        cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{f2(cx - side / 2)} {f2(cy - side / 2)} {f2(side)} {f2(side)}">'
               f'{prefix_ids(part.inner(v), "q")}</svg>')
    open(p, 'w').write(svg)
    return p


# ------------------------------------------------------------------ icon canvases (app icons, avatars, favicons)
def icon_ground(c):
    """'light' or 'dark' — where the full-colour compact mark has more presence (area-weighted contrast)"""
    ink = c.ink
    lv = (c.b.mark or {}).get('levels', {})
    faces = lv.get('simplified') or lv.get('master') or []
    if c.b.logo_type == 'wordmark' or not faces:
        return 'light'
    def score(ground, key):
        tot = sum(f.get('area', 1) for f in faces) or 1
        return sum(f.get('area', 1) * min(contrast(f.get(key) or f['color'], ground), 7) for f in faces) / tot
    sl, sd = score(ink.light, 'color'), score(ink.dark, 'on_dark')
    return 'dark' if sd > sl * 1.08 else 'light'


def mark_on_canvas(c, S, ground, variant, r_frac, h_frac, part=None, cx=None, cy=None):
    """compact mark optically centred on an S×S canvas: farthest point ≤ r_frac·S from the centre, box ≤ h_frac·S"""
    part = part or c.parts['compact']
    ox, oy = part.oc
    s = min(r_frac * S / part.far_radius(ox, oy), h_frac * S / part.h, h_frac * S / part.w)
    it = place_centre(part, S / 2 if cx is None else cx, S / 2 if cy is None else cy, s)
    return it.svg(variant, 'm', gid='mark')


def canvas(S, inner, title, bg=None, shape=None, desc=''):
    out = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {S} {S}" role="img" aria-labelledby="t"><title id="t">{F.esc(title)}</title>']
    if desc: out.append(f'<desc>{F.esc(desc)}</desc>')
    if bg and shape: out.append(shape.replace('/>', f' fill="{bg}"/>'))
    elif bg: out.append(f'<rect id="background" width="{S}" height="{S}" fill="{bg}"/>')
    out.append(inner)
    out.append('</svg>\n')
    return ''.join(out)


def build_favicons(c):
    b, ink = c.b, c.ink
    D = lambda *a: b.path('LOGO', 'FAVICON', *a)
    wm = b.logo_type == 'wordmark'
    g = icon_ground(c)
    gcol, gvar = (ink.dark, 'on-dark') if g == 'dark' else (ink.light, 'color')
    c.icon = {'ground': g, 'ground_hex': gcol, 'variant': gvar}
    T = b.name
    # ---- icon.svg (scalable favicon). Symbol logos: transparent mark that swaps to its on-dark colours in dark browser UI.
    if wm:
        svg, _ = c.compact_lockup.svg('color', F.esc(f'{T} — icon'), pfx='i')
    else:
        part = c.parts['compact']
        x0, y0, x1, y1 = part.box
        side = max(x1 - x0, y1 - y0); cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
        light, dark = part.inner('color'), part.inner('on-dark')
        lf = re.findall(r'fill="(#[0-9A-Fa-f]{3,8})"', light); df = re.findall(r'fill="(#[0-9A-Fa-f]{3,8})"', dark)
        css = []
        if len(lf) == len(df):
            k = [0]
            def tag(m):
                i = k[0]; k[0] += 1
                if lf[i].upper() != df[i].upper():
                    css.append(f'.d{i}{{fill:{df[i]};stroke:{df[i]}}}' if f'stroke="{lf[i]}"' in light else f'.d{i}{{fill:{df[i]}}}')
                    return f'class="d{i}" {m.group(0)}'
                return m.group(0)
            light = re.sub(r'fill="#[0-9A-Fa-f]{3,8}"', tag, light)
        style = f'<style>@media (prefers-color-scheme: dark){{{"".join(css)}}}</style>' if css else ''
        svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{f2(cx - side / 2)} {f2(cy - side / 2)} {f2(side)} {f2(side)}">'
               f'<title>{F.esc(T)}</title>{style}{prefix_ids(light, "i")}</svg>\n')
    F.write(D('icon.svg'), svg)
    # ---- favicon PNGs 16/32/48 (transparent; wordmark: the container itself)
    for s in (16, 32, 48):
        src = square_svg(c, None, 'color', 'compact-color', lockup=c.compact_lockup) if wm else square_svg(c, c.parts['compact'], 'color', 'compact-color')
        job(c, src, D(f'favicon-{s}.png'), s, s)
    # ---- app icon master (opaque) → apple-touch 180
    shape, shape_name = container_path(b, 0, 0, 1024)
    if wm:
        cont, letter = c.compact_lockup.colours('color')
        app = canvas(1024, letter_on(c, 1024, letter, 0.5), f'{T} — app icon', bg=cont,
                     desc='Monogram on the primary field. Opaque square; the OS applies its own mask.')
        mask_svg = canvas(512, letter_on(c, 512, letter, 0.36), f'{T} — maskable icon', bg=cont,
                          desc='PWA maskable icon: the monogram stays inside the 80% safe circle.')
        any_svg = canvas(512, letter_on(c, 512, letter, 0.46), f'{T} — app icon (any)', bg=cont, shape=container_path(b, 0, 0, 512)[0],
                         desc=f'Monogram in the brand container ({shape_name}) on transparent.')
        theme_bg = cont
    else:
        app = canvas(1024, mark_on_canvas(c, 1024, gcol, gvar, 0.34, 0.62), f'{T} — app icon', bg=gcol,
                     desc='Compact mark optically centred on the brand ground. Opaque; the OS applies its own mask.')
        mask_svg = canvas(512, mark_on_canvas(c, 512, gcol, gvar, 0.29, 0.56), f'{T} — maskable icon', bg=gcol,
                          desc='PWA maskable icon: the farthest point of the mark sits at 72% of the 80% safe-circle radius.')
        any_svg = canvas(512, mark_on_canvas(c, 512, gcol, gvar, 0.3, 0.58), f'{T} — app icon (any)', bg=gcol,
                         shape=container_path(b, 0, 0, 512)[0], desc=f'Compact mark in the brand container ({shape_name}) on transparent.')
        theme_bg = gcol
    F.write(D('app-icon.svg'), app); F.write(D('maskable.svg'), mask_svg); F.write(D('app-icon-any.svg'), any_svg)
    job(c, D('app-icon.svg'), D('apple-touch-icon.png'), 180, 180, transparent=False)
    for s in (192, 512):
        job(c, D('maskable.svg'), D(f'maskable-{s}.png'), s, s, transparent=False)
        job(c, D('app-icon-any.svg'), D(f'android-chrome-{s}.png'), s, s)
    c.icon.update({'shape': shape_name, 'theme_bg': theme_bg})
    short = b.name if len(b.name) <= 12 else (b.config.get('wordmark', {}).get('monogram') or b.name.split()[0])[:12]
    manifest = {'name': b.name, 'short_name': short, 'description': (b.content.get('brand', {}) or {}).get('tagline') or b.brand.get('tagline', ''),
                'lang': b.lang, 'start_url': '/', 'display': 'standalone',
                'theme_color': (b.theme or {}).get('brand-primary') or ink.P, 'background_color': theme_bg,
                'icons': [{'src': 'android-chrome-192.png', 'sizes': '192x192', 'type': 'image/png', 'purpose': 'any'},
                          {'src': 'android-chrome-512.png', 'sizes': '512x512', 'type': 'image/png', 'purpose': 'any'},
                          {'src': 'maskable-192.png', 'sizes': '192x192', 'type': 'image/png', 'purpose': 'maskable'},
                          {'src': 'maskable-512.png', 'sizes': '512x512', 'type': 'image/png', 'purpose': 'maskable'},
                          {'src': 'icon.svg', 'sizes': 'any', 'type': 'image/svg+xml'}]}
    F.write(D('site.webmanifest'), json.dumps(manifest, indent=2, ensure_ascii=False) + '\n')
    snippet = (f'<!-- {b.name} — favicon set (logo-system module). Copy LOGO/FAVICON/* to the site root or adjust the paths. -->\n'
               '<link rel="icon" href="/favicon.ico" sizes="48x48">\n<link rel="icon" href="/icon.svg" type="image/svg+xml">\n'
               '<link rel="icon" href="/favicon-32.png" type="image/png" sizes="32x32">\n<link rel="icon" href="/favicon-16.png" type="image/png" sizes="16x16">\n'
               '<link rel="apple-touch-icon" href="/apple-touch-icon.png">\n<link rel="manifest" href="/site.webmanifest">\n'
               f'<meta name="theme-color" content="{(b.theme or {}).get("background") or ink.PA}" media="(prefers-color-scheme: light)">\n'
               f'<meta name="theme-color" content="{ink.dark}" media="(prefers-color-scheme: dark)">\n')
    F.write(D('head-snippet.html'), snippet)
    c.manifest = manifest


def letter_on(c, S, colour, frac):
    """wordmark monogram centred on an S canvas, height ≤ frac·S"""
    part = c.parts['compact']
    s = min(frac * S / part.h, frac * 1.15 * S / part.w)
    it = place_centre(part, S / 2, S / 2, s)
    inner = recolor_all(part.inner('foundation'), colour)
    tx = it.x - part.box[0] * s; ty = it.y - part.box[1] * s
    return f'<g id="mark" transform="translate({f2(tx)} {f2(ty)}) scale({s:.6f})">{prefix_ids(inner, "m")}</g>'


def build_ico(c):
    from PIL import Image
    D = lambda *a: c.b.path('LOGO', 'FAVICON', *a)
    try:
        ims = [Image.open(D(f'favicon-{s}.png')).convert('RGBA') for s in (16, 32, 48)]
        ims[2].save(D('favicon.ico'), format='ICO', sizes=[(16, 16), (32, 32), (48, 48)], append_images=ims[:2])
    except Exception as e:
        print('logo-system: favicon.ico skipped —', e)


def build_avatars(c):
    b, ink = c.b, c.ink
    A = lambda *a: b.path('LOGO', 'AVATARS', *a)
    wm = b.logo_type == 'wordmark'
    S = 1080
    ways = [('paper', ink.light, 'color'), ('primary', ink.P, ink.on_primary_variant), ('foundation', ink.dark, 'on-dark')]
    c.avatars = []
    for name, bg, v in ways:
        if wm:
            col = {'paper': ink.P if ink.primary_ok else ink.F, 'primary': ink.on_primary if contrast(ink.on_primary, ink.P) >= 3 else ink.PA,
                   'foundation': ink.PA}[name]
            inner = letter_on(c, S, col, 0.42)
        else:
            inner = mark_on_canvas(c, S, bg, v, 0.31, 0.6)
        svg = canvas(S, inner, f'{b.name} — profile image ({name})', bg=bg,
                     desc='Square profile image that survives circular crops: compact mark optically centred, farthest point at 62% of the circle radius.')
        p = A(f'avatar-{name}.svg'); F.write(p, svg)
        for s in (400, 1080):
            job(c, p, A(f'avatar-{name}-{s}.png'), s, s, transparent=False)
        c.avatars.append({'name': name, 'ground': bg, 'svg': rel(c, p), 'png': [rel(c, A(f'avatar-{name}-{s}.png')) for s in (400, 1080)]})


# ------------------------------------------------------------------ cleanup / index
def clean(c):
    b = c.b
    for d in OWNED:
        shutil.rmtree(b.path('LOGO', d), ignore_errors=True)
    for f in ('logo-sheet.html', 'logo-sheet.png'):
        if os.path.exists(b.path('LOGO', f)): os.remove(b.path('LOGO', f))
    idx = b.path('SOURCE', 'JSON', 'logo-system.json')
    if os.path.exists(idx):
        try:
            for f in json.load(open(idx)).get('generated_png', []):
                p = b.path(f)
                if os.path.exists(p) and 'original' not in os.path.basename(p): os.remove(p)
        except Exception: pass


def write_index(c):
    b = c.b
    lk = {}
    for l in c.lockups:
        lk[l.name] = {'title': l.title, 'use': l.use, 'kind': l.kind, 'aspect': round(l.aspect, 4),
                      'size_units': [round(v, 2) for v in l.size], 'min': c.mins[l.name],
                      'clear_space_units': round(c.clear[l.name], 2), 'construction': {k: (round(v, 3) if isinstance(v, float) else v) for k, v in l.notes.items()},
                      'files': c.files[l.name]}
    rec = c.primary
    data = {
        'module': 'logo-system', 'version': '1.0.0', 'logo_type': b.logo_type, 'slug': c.slug,
        'unit': 'X = cap height of the name / lettering = 100 lockup units',
        'primary': rec, 'variants': c.ink.variants(),
        'grounds': {'light': c.ink.light, 'dark': c.ink.dark, 'primary': c.ink.P, 'on_primary_variant': c.ink.on_primary_variant},
        'recommend': {
            'light': c.files[rec]['color']['svg'], 'dark': c.files[rec]['on-dark']['svg'],
            'primary_field': c.files[rec][c.ink.on_primary_variant]['svg'],
            'wide': c.files[c.wide]['color']['svg'], 'square': c.files[c.square]['color']['svg'],
            'compact': c.files['compact' if 'compact' in c.files else 'symbol']['color']['svg']},
        'rules': c.rules, 'clear_space': c.clear_rule, 'lockups': lk,
        'favicon': {'dir': 'LOGO/FAVICON', 'ground': c.icon.get('ground'), 'shape': c.icon.get('shape'), 'manifest': 'LOGO/FAVICON/site.webmanifest'},
        'avatars': c.avatars,
        'guides': ['LOGO/GUIDES/' + g for g in c.guides], 'sheet': 'LOGO/logo-sheet.html',
        'generated_png': sorted(rel(c, p) for p in c.png_written),
    }
    F.write(b.path('SOURCE', 'JSON', 'logo-system.json'), json.dumps(data, indent=1, ensure_ascii=False) + '\n')
    js = {k: v for k, v in data.items() if k != 'generated_png'}
    F.write(b.path('SOURCE', 'JS', f'{b.p}-logo-system.js'),
            f'/* {b.name} — logo-system index (generated). Paths are repo-relative; prefix them with the page\'s path to the repo root. */\n'
            f'window.{b.G}_LOGO = {json.dumps(js, ensure_ascii=False)};\n')
    return data


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--repo', required=True)
    ap.add_argument('--svg-only', action='store_true', help='write SVG/HTML only, no PNG rendering')
    ap.add_argument('--no-sheet', action='store_true', help='skip the logo sheet render')
    a = ap.parse_args()
    t0 = time.time()
    c = Ctx(); c.b = b = F.load(a.repo); c.ink = Ink(b); c.slug = slugify(b); c.rules = spec_rules(b)
    c.jobs, c.png_written = [], []
    c.tmp = tempfile.mkdtemp(prefix='logo-system-')
    try:
        clean(c)
        c.parts = load_parts(b, c.ink)
        c.lockups, c.primary = build_lockups(b, c.parts, c.ink)
        c.compact_lockup = next((l for l in c.lockups if l.name == 'compact'), None)
        c.mins = {l.name: min_size(l, c.rules) for l in c.lockups}
        sym_short = None
        if 'mark' in c.parts: sym_short = min(c.parts['mark'].w, c.parts['mark'].h)
        c.clear = {}
        for l in c.lockups:
            if l.kind in ('symbol', 'compact'):
                w, h = l.size
                c.clear[l.name] = c.rules['clear_pct'] / 100 * min(w, h)
            else:
                c.clear[l.name] = X
        c.clear_rule = {'lockups': '1X (cap height of the name / lettering) on every side',
                        'symbol': f'{c.rules["clear_pct"]}% of the shorter side of the mark'}
        wide = sorted([l for l in c.lockups if l.kind == 'lockup'], key=lambda l: -l.aspect)
        c.wide = wide[0].name if wide else c.primary
        sq = sorted([l for l in c.lockups if l.kind == 'lockup'], key=lambda l: abs(math.log(l.aspect)))
        c.square = sq[0].name if sq else c.primary
        build_lockup_files(c)
        build_favicons(c)
        build_avatars(c)
        c.guides = pages.build_guides(c, job)
        if not a.no_sheet:
            pages.build_sheet(c, job)
        if not a.svg_only:
            F.shots(c.jobs)
            build_ico(c)
        data = write_index(c)
        docs.write_readmes(c, data)
    finally:
        shutil.rmtree(c.tmp, ignore_errors=True)
    n_svg = sum(len(v) for v in c.files.values())
    print(f'logo-system: {len(c.lockups)} lockups × {len(c.ink.variants())} colourways = {n_svg} SVG · {len(c.jobs)} PNG · '
          f'{len(c.guides)} guides · favicon set · {len(c.avatars) * 2} avatars · sheet ({time.time() - t0:.1f}s)')


if __name__ == '__main__':
    main()
