#!/usr/bin/env python3
"""
build_spec.py — write SOURCE/CONFIG/production-spec.md: the compact rulebook every asset (and every agent) follows.

usage: python3 scripts/build_spec.py --repo ../ACME-BRAND

Generated entirely from the data (config, DNA, profile, logo parts, tokens, contrast report), so it is always complete
and true. The art director may edit it: once the line `<!-- generated by build_spec -->` is removed, the file is never
overwritten again. Sections: idea · sources · logo construction · colour · type · shape grammar · icons · patterns &
graphics · imagery · motion · data · voice & content · accessibility · deliverables · naming & delivery.
"""
import argparse, json, os
MARK = '<!-- generated by build_spec -->'

def J(p, d=None):
    return json.load(open(p)) if os.path.exists(p) else (d if d is not None else {})

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--repo', required=True); a = ap.parse_args(); R = lambda *x: os.path.join(a.repo, *x)
    out = R('SOURCE', 'CONFIG', 'production-spec.md')
    if os.path.exists(out) and MARK not in open(out).read(): print('production-spec.md was edited by hand — left unchanged'); return
    C = J(R('SOURCE', 'CONFIG', 'brand.config.json')); b = C['brand']; p = b.get('prefix', 'bx'); G = b.get('global', 'BX')
    D = J(R('SOURCE', 'CONFIG', 'design-dna.json')); P = J(R('SOURCE', 'CONFIG', 'profile.json')); L = J(R('SOURCE', 'JSON', 'logo-parts.json'))
    M = J(R('SOURCE', 'JSON', 'mark.json')); T = J(R('SOURCE', 'JSON', 'design-tokens.json')); CR = J(R('COLORS', 'contrast-report.json'))
    COL = J(R('COLORS', 'colors.json')); WM = J(R('SOURCE', 'JSON', 'wordmark-paths.json'))
    lt = L.get('logo_type', C['logo'].get('type', 'symbol')); roles = C['roles']; pal = {c['key']: c for c in C['palette']}
    prim, found, paper = pal[roles['primary']], pal[roles['foundation']], pal[roles['paper']]; acc = pal.get(roles.get('accent', ''), None)
    lay = L.get('layout', {}); fams = {f['role']: f for f in C['fonts'].get('families', [])}
    typ = T.get('typography', {})
    def tline(k):
        t = typ.get(k, {}).get('$value', {}); tf = typ.get(k, {}).get('$extensions', {}).get('textTransform', 'none')
        return f"`{k}` — {t.get('fontFamily', '').strip('{}').replace('font.family.', '')} {t.get('fontWeight', '')} · {t.get('fontSize', '')} / {t.get('lineHeight', '')} · tracking {t.get('letterSpacing', '')}{' · ' + tf if tf != 'none' else ''}"
    nmaster = len(M.get('levels', {}).get('master', [])); nsimple = len(M.get('levels', {}).get('simplified', []))
    idea = b.get('brand_idea') or f"‹brand idea — write it in the concept phase (references/playbook/03)›"
    s = [MARK, f'# {b["name"]} — Production Spec', '',
         '> The rules every asset follows. Generated from SOURCE/CONFIG (config, design DNA, profile) and the measured logo.',
         '> Edit the config and regenerate — or delete the marker line above to take this file over by hand.', '',
         '## 0. Idea', '', f'**{idea}**' + (f' — principle **{b["principle"]}**' if b.get('principle') else ''), '',
         f'{b["name"]} ({b.get("legal_name", b["name"])}) · profile **{P.get("title", b.get("profile", ""))}** · audiences: {", ".join(P.get("audiences", []))}.',
         f'The logo is a **{lt}** with **{D.get("geometry", "")}** geometry and **{D.get("complexity", "")}** rendering; everything below is derived from it.', '',
         '## 1. Sources of truth', '', '| What | File |', '|---|---|',
         '| Original artwork (primary logo, never altered) | `LOGO/PNG/*-original-artwork.*` |',
         f'| Vector mark ({nmaster} shapes master · {nsimple} simplified) | `SOURCE/JSON/mark.json` · `SOURCE/JS/mark-data.js` · `{G}.markSVG()` / `<{p}-mark>` |',
         '| Logo parts & original layout | `SOURCE/JSON/logo-parts.json` |', '| Lettering (traced/typeset) | `SOURCE/SVG/*.svg` · `SOURCE/JS/wordmark-data.js` · `' + G + '.wordmarkSVG()` |',
         '| Design DNA | `SOURCE/CONFIG/design-dna.json` · `SOURCE/JS/dna-data.js` |', '| Tokens | `SOURCE/JSON/design-tokens.json` · `SOURCE/CSS/tokens.css` · `colors.css` |',
         f'| Core CSS / JS | `SOURCE/CSS/{p}-core.css` · `SOURCE/JS/{p}-mark.js` |', '| Content (shared by every module) | `SOURCE/CONFIG/content.json` · `SOURCE/JS/content-data.js` |',
         '| Profile (deliverables) | `SOURCE/CONFIG/profile.json` |', '',
         '## 2. Logo', '']
    if lt == 'combination':
        s += [f'- Original lockup: **{L.get("arrangement", "")}**, symbol {lay.get("symbol_side", "")}, gap = {lay.get("gap_rel_symbol_height", "?")} × symbol height, lettering height = {lay.get("lettering_height_rel_symbol", "?")} × symbol height, alignment {lay.get("align", "")}. Rebuilt in `LOGO/SVG/logo-original*.svg` — this is the primary lockup.',
              '- Alternates (logo-system module) keep these proportions; the lettering is the traced original, never re-typeset.']
    elif lt == 'wordmark':
        s += ['- The lettering IS the logo (`LOGO/SVG/logo-original*.svg`). Compact mark for avatars/favicons = the traced first letter (`LOGO/SVG/compact*.svg`).',
              '- Never re-typeset or re-space the lettering; typeset text in the display font is for headlines only.']
    elif lt == 'emblem':
        s += ['- The emblem is one unit (lettering inside the frame). It is not split. Use the simplified emblem below ~48 px; below ~24 px use the frame/silhouette only.',
              '- The name in the display font (SOURCE/SVG/wordmark-*.svg) accompanies the emblem in horizontal layouts.']
    else:
        s += ['- The symbol stands alone; the name is set in the display font as an outlined wordmark (`SOURCE/SVG/wordmark-*.svg`) for lockups.']
    s += ['- **Clear space** = 25 % of the mark\'s shorter side on every side (lockups: the cap height of the lettering).',
          '- **Minimum size**: master ≥ 48 px / 12 mm; simplified/compact ≥ 16 px / 5 mm; lockups ≥ 120 px / 30 mm wide.',
          f'- **Optical centre** of the mark: {M.get("optical_center", [0.5, 0.5])} (x, y of the viewBox) — align text to it, not to the box.',
          '- Backgrounds: light → full colour · dark → `symbol-on-dark` / `logo-original-on-dark` · primary fields → one-colour white · photos → a calm area or a panel.',
          '- Never: stretch, rotate, recolour parts arbitrarily, add effects/shadows, outline the full-colour mark, rearrange the lockup, place on busy images.', '',
          '## 3. Colour', '', '| Name | HEX | Role | on paper | white text |', '|---|---|---|---|---|']
    for c in COL.get('palette', []):
        s.append(f"| {c['name']} | `{c['hex']}` | {c.get('role', '')} | {c['contrast']['on_paper']}:1 | {c['contrast']['white_text']} |")
    ur = COL.get('usage_ratio', {})
    s += ['', 'Ratio: ' + ' · '.join(f'{k} {v}' for k, v in ur.items()) + '. One clearly dominant brand-colour element per composition.',
          f'Text colours come from the theme tokens only (`--color-text-*`), never raw palette values. Auto-fixed pairs: {len(COL.get("auto_fixes", []))} (see COLORS/contrast-report.json).',
          'Error/warning/success/info always pair colour with an icon and text. CMYK values are conversions — proof on press; no invented Pantone references.', '',
          '## 4. Typography', '', '| Role | Family |', '|---|---|'] + [f"| {r} | {f['family']} ({', '.join(f.get('subsets', []))}) |" for r, f in fams.items()] + ['',
          *[f'- {tline(k)}' for k in ('display-xl', 'h1', 'h2', 'h3', 'body', 'small', 'label', 'eyebrow', 'button', 'data')], '',
          f'Display case: **{D.get("type_voice", {}).get("display_case", "sentence")}**. Body 17 px / 1.6, measure ≤ 68ch. Numbers in data: tabular. All styles exist as `.{p}-<style>` classes and `--type-<style>-*` tokens.', '',
          '## 5. Shape grammar (from the design DNA)', '',
          f'- Corners: **{D.get("corner", {}).get("style", "")}** — {D.get("corner", {}).get("note", "")} Use `.{p}-shape` for every container; radius/cut tokens: `--radius-*`, `--cut-*`.',
          f'- Angles: chamfer {D.get("angles", {}).get("cut")}°, crop {D.get("angles", {}).get("crop")}°, shallow band {D.get("angles", {}).get("shallow")}° (`--angle-*`).',
          f'- Strokes: icons {D.get("stroke", {}).get("icon_px_at_24")} px @24, caps {D.get("stroke", {}).get("cap")}, joins {D.get("stroke", {}).get("join")} (`--stroke-*`). Rules {D.get("stroke", {}).get("rule_px")} px.',
          f'- Shadows: **{D.get("shadow_style", "")}** (`--shadow-1…3`). Composition: **{D.get("composition", "")}**. Density: **{D.get("density", "")}**.', '',
          '## 6. Icons', '', f'Grid 24 px, 2 px padding, stroke and corners as above, `currentColor`. Sets needed by the profile: {", ".join(P.get("icons", []))}. Labels always accompany meaning-carrying icons.', '',
          '## 7. Patterns & graphics', '', f'Families: {", ".join(D.get("patterns", []))}. Motifs: {", ".join(D.get("motifs", []))}.',
          'Built from the mark geometry and the DNA angles; max one pattern per composition; patterns never sit behind body text without a solid panel.', '',
          '## 8. Imagery', '', f'Crop: **{D.get("imagery", {}).get("crop", "")}** (`.{p}-crop`). Direction: {D.get("imagery", {}).get("direction", "")}. Treatments: {", ".join(D.get("imagery", {}).get("treatments", []))}.',
          'Placeholders are clearly labelled; real people need consent; no stock clichés.', '',
          '## 9. Motion', '', f'Character **{D.get("motion", {}).get("character", "")}** — {D.get("motion", {}).get("signature", "")}. Tokens `--duration-*`, `--ease-*`; reduced-motion always respected (no motion, no parallax, instant states).', '',
          '## 10. Data', '', f'Charts needed: {", ".join(P.get("dataviz", [])) or "none"}. Categorical order: primary, accent, then secondary palette colours, then ramp steps; direct labels over legends; source line on every chart.', '',
          '## 11. Voice & content', '', f'Voice: {", ".join(P.get("voice", {}).get("traits", []))}. Avoid: {", ".join(P.get("voice", {}).get("avoid", []))}. CTAs: {", ".join(P.get("voice", {}).get("cta", []))}.',
          f'Labels: ' + ', '.join(f'{k} → "{v}"' for k, v in P.get('labels', {}).items()) + '.', 'All copy comes from content.json; sample content is marked as such and never presented as real.', '',
          '## 12. Accessibility', '', 'WCAG 2.2 AA: text ≥ 4.5:1 (large 3:1), UI and focus ≥ 3:1, visible focus everywhere, keyboard paths, semantic HTML, alt text, reduced motion, language attributes per text, no text in images without an equivalent.', '',
          '## 13. Deliverables (profile)', '']
    for k in ('pages', 'social', 'post_types', 'presentation', 'print', 'documents', 'events', 'merch', 'environment'):
        if P.get(k): s.append(f'- **{k.replace("_", " ")}**: {", ".join(P[k])}')
    s += ['', '## 14. Naming & delivery', '', '- kebab-case file names, no spaces; `<thing>-<variant>-<size>.<ext>`; one README per top folder.',
          '- HTML works from `file://` (classic scripts, inline SVG/data, no fetch). Renders via Playwright after `document.fonts.ready`.',
          '- Deliver as zip parts ≤ 18 MB + merge commands (`scripts/split_zip.py`).']
    open(out, 'w').write('\n'.join(s) + '\n'); print('production-spec.md written')

if __name__ == '__main__':
    main()
