#!/usr/bin/env python3
"""
build_docs.py — write the repository README and a README in every top-level folder that lacks one.

usage: python3 scripts/build_docs.py --repo ../ACME-BRAND

Hand-written READMEs are never touched. Generated ones carry the marker <!-- generated by build_docs --> and are
refreshed on every run (so inventories stay true after modules add files). Run it last (lite.py does).
"""
import argparse, collections, json, os, re

MARK = '<!-- generated by build_docs -->'
PURPOSE = {
    'BRAND-BOOK': 'The brand guidelines: foundation board, brand book (HTML/PDF) and the showcase page.',
    'LOGO': 'Every logo asset: the untouched original artwork, vector rebuilds, symbol variants, lockups, one-colour, favicons and app icons.',
    'COLORS': 'The colour system: palette with HEX/RGB/CMYK/HSL, ramps, semantic colours, light/dark/contrast themes and the WCAG contrast report.',
    'TYPOGRAPHY': 'Type specimens, pairing rationale and usage rules (font files live in SOURCE/FONTS).',
    'ICONS': 'The icon set (SVG, sprite, JS map) drawn on the brand stroke and corner rules.',
    'PATTERNS': 'Repeatable patterns derived from the mark geometry (SVG tiles, PNG previews).',
    'GRAPHICS': 'Graphic devices and compositions built from the brand motifs.',
    'PHOTOGRAPHY': 'Photography direction, crops/masks and treatments (placeholders until real photos arrive).',
    'SOCIAL-MEDIA': 'Social templates (HTML engine + rendered PNGs) for every format the profile needs.',
    'PRESENTATION': 'The slide system: HTML deck, PDF export and PowerPoint file.',
    'PRINT': 'Print collateral and documents (press-ready PDFs with bleed, DOCX templates).',
    'EVENTS': 'Event materials: badges, signage, backdrops, banners.',
    'MERCH': 'Merchandise artwork and mockups.',
    'ENVIRONMENT': 'Environmental graphics: signage, walls, windows, vehicles.',
    'UI-DESIGN-SYSTEM': 'Design tokens (DTCG JSON, CSS, Tailwind) and the UI component library with its gallery.',
    'WEBSITE': 'A static website prototype built from the UI kit and the shared content.',
    'MOTION': 'Motion principles, CSS/JS motion utilities, logo animations and transitions.',
    'GENERATIVE': 'Generative tools that create on-brand graphics from the mark and motifs.',
    'DATA-VIZ': 'Chart library, infographic components and data-visualisation rules.',
    'MOCKUPS': 'Mockups that show the system in context.',
    'SHOWCASE': 'A single page that presents the whole system (also portable/offline).',
    'SOURCE': 'Single source of truth: config, content, DNA, tokens, CSS/JS engines, fonts, SVG masters and the scripts that regenerate everything.',
}

def inventory(path):
    sub = collections.Counter(); ext = collections.Counter(); files = []
    for d, ds, fs in os.walk(path):
        ds[:] = [x for x in ds if not x.startswith(('_work', 'node_modules', '__pycache__'))]
        for f in fs:
            if f == 'README.md': continue
            rel = os.path.relpath(os.path.join(d, f), path); files.append(rel)
            sub[rel.split(os.sep)[0] if os.sep in rel else '.'] += 1; ext[os.path.splitext(f)[1].lower() or '(none)'] += 1
    return sub, ext, sorted(files)

def writable(p):
    return not os.path.exists(p) or MARK in open(p, encoding='utf-8', errors='ignore').read()

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--repo', required=True); a = ap.parse_args(); R = lambda *x: os.path.join(a.repo, *x)
    C = json.load(open(R('SOURCE', 'CONFIG', 'brand.config.json'))); b = C['brand']
    dna = json.load(open(R('SOURCE', 'CONFIG', 'design-dna.json'))) if os.path.exists(R('SOURCE', 'CONFIG', 'design-dna.json')) else {}
    tops = sorted(d for d in os.listdir(a.repo) if os.path.isdir(R(d)) and not d.startswith('.'))
    for t in tops:
        p = R(t, 'README.md')
        if not writable(p): continue
        sub, ext, files = inventory(R(t))
        if not files: continue
        lines = [MARK, f'# {t.replace("-", " ").title()}', '', PURPOSE.get(t, f'{t} assets of the {b["name"]} brand system.'), '',
                 f'**{len(files)} files** · ' + ' · '.join(f'{n} {e}' for e, n in ext.most_common(8)), '', '| Folder | Files |', '|---|---|']
        lines += [f'| `{k}/` | {v} |' if k != '.' else f'| (this folder) | {v} |' for k, v in sorted(sub.items())]
        key = [f for f in files if f.lower().endswith(('.html', '.pdf', '.pptx', '.docx'))][:12] or files[:12]
        lines += ['', '## Key files', ''] + [f'- `{f}`' for f in key]
        open(p, 'w').write('\n'.join(lines) + '\n')
    p = R('README.md')
    if writable(p):
        pal = C.get('palette', []); fams = C.get('fonts', {}).get('families', [])
        content = json.load(open(R('SOURCE', 'CONFIG', 'content.json'))) if os.path.exists(R('SOURCE', 'CONFIG', 'content.json')) else {}
        rows = []
        for t in tops:
            sub, ext, files = inventory(R(t))
            if files: rows.append(f'| [`{t}/`]({t}/) | {len(files)} | {PURPOSE.get(t, "")} |')
        start = [x for x in ('SHOWCASE/index.html', 'BRAND-BOOK/brand-book.pdf', 'BRAND-BOOK/foundation-board.png', 'WEBSITE/index.html', 'UI-DESIGN-SYSTEM/components/index.html') if os.path.exists(R(x))]
        lines = [MARK, f'# {b["name"]} — Brand System', '', f'_{b.get("tagline", "")}_', '',
                 f'{b.get("legal_name", b["name"])} · profile **{b.get("profile", "")}** · logo **{C["logo"].get("type", "")}** · languages {", ".join(b.get("languages", []))}', '',
                 '## Start here', ''] + [f'- [{x}]({x})' for x in start] + ['',
                 '## The system in one paragraph', '',
                 (f'The design DNA comes from the logo itself: **{dna.get("geometry", "")}** geometry → **{dna.get("corner", {}).get("style", "")}** corners, '
                  f'**{dna.get("imagery", {}).get("crop", "")}** image crops, **{dna.get("motion", {}).get("character", "")}** motion, patterns '
                  f'{", ".join(dna.get("patterns", [])[:3])}. ' if dna else '') +
                 f'Colours are sampled from the artwork; fonts are open-source ({", ".join(sorted({f["family"] for f in fams}))}).', '',
                 '| Colour | HEX | Role |', '|---|---|---|'] + [f'| {c["name"]} | `{c["hex"]}` | {c.get("role", "")} |' for c in pal] + ['',
                 '## Contents', '', '| Folder | Files | What |', '|---|---|---|'] + rows + ['',
                 '## Regenerate', '', 'Everything generated is reproducible from `SOURCE/CONFIG/` with the bundled scripts:', '', '```bash',
                 'python3 SOURCE/SCRIPTS/forge/scripts/foundation.py --config SOURCE/CONFIG/brand.config.json --repo .   # foundations',
                 'python3 SOURCE/SCRIPTS/forge/scripts/lite.py --repo .                                                 # every module', '```', '',
                 '## Notes', '',
                 ('- **Sample content.** Texts, people, numbers and events are placeholders generated from the company profile — replace them in `SOURCE/CONFIG/content.json` and regenerate.' if content.get('_sample') else '- Content comes from `SOURCE/CONFIG/content.json`.'),
                 '- The original logo artwork in `LOGO/` is the primary logo and is never altered; vectors are faithful rebuilds.',
                 '- Fonts are open-source (SIL OFL) and self-hosted in `SOURCE/FONTS/` with their licences.',
                 '- CMYK values are conversions; proof on press. No Pantone references are invented.']
        open(p, 'w').write('\n'.join(lines) + '\n')
    print(f'docs: README + {len(tops)} folder READMEs checked')

if __name__ == '__main__':
    main()
