#!/usr/bin/env python3
"""
fetch_fonts.py — self-host open-source fonts (Google Fonts families via Fontsource on npm).

Reads brand.config.json → fonts.families[]:
  { "role": "sans", "family": "Figtree",
    "package": "@fontsource-variable/figtree",   # or "@fontsource/<slug>" for static-only fonts
    "css": ["full.css"],                             # which Fontsource CSS file(s) to use
                                                     # variable: index.css (wght) · wght.css · full.css (all axes) · standard.css (wght+wdth) · wght-italic.css
                                                     # static:   400.css, 700.css, 400-italic.css …
    "subsets": ["latin", "latin-ext", "cyrillic"] }  # see the package's metadata.json "subsets"

Writes into the brand repository:
  SOURCE/FONTS/*.woff2 + OFL-<Family>.txt (licence)
  SOURCE/CSS/fonts.css   (@font-face with unicode-range; family names without the " Variable" suffix)
Requires npm (registry access). Usage: python3 scripts/fetch_fonts.py --config brand.config.json --repo ../ACME-BRAND
Tip: the npm registry is usually reachable even where fonts.googleapis.com is blocked.
"""
import argparse, json, os, re, shutil, subprocess, tempfile

def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--config', required=True); ap.add_argument('--repo', required=True)
    ap.add_argument('--cache', default=os.path.join(tempfile.gettempdir(), 'brand-forge-fonts'))
    a = ap.parse_args()
    C = json.load(open(a.config)); fams = C['fonts']['families']
    os.makedirs(a.cache, exist_ok=True)
    if not os.path.exists(os.path.join(a.cache, 'package.json')):
        subprocess.check_call(['npm', 'init', '-y'], cwd=a.cache, stdout=subprocess.DEVNULL)
    pkgs = sorted({f['package'] for f in fams})
    subprocess.check_call(['npm', 'install', '--silent', '--no-audit', '--no-fund'] + pkgs, cwd=a.cache)
    FD = os.path.join(a.repo, 'SOURCE', 'FONTS'); CD = os.path.join(a.repo, 'SOURCE', 'CSS')
    os.makedirs(FD, exist_ok=True); os.makedirs(CD, exist_ok=True)
    out = ['/* Self-hosted open-source fonts (SIL OFL 1.1) — generated by scripts/fetch_fonts.py from Fontsource.\n   Font files live in ../FONTS/ (relative to this file). */\n']
    copied = 0
    for f in fams:
        pdir = os.path.join(a.cache, 'node_modules', *f['package'].split('/'))
        meta = json.load(open(os.path.join(pdir, 'metadata.json'))) if os.path.exists(os.path.join(pdir, 'metadata.json')) else {}
        known = sorted(meta.get('subsets', []) or f['subsets'], key=len, reverse=True)
        slug = f['package'].split('/')[-1]
        lic = os.path.join(pdir, 'LICENSE')
        if os.path.exists(lic): shutil.copy(lic, os.path.join(FD, 'OFL-' + re.sub(r'\W+', '', f['family']) + '.txt'))
        for cssname in f.get('css', ['index.css']):
            txt = open(os.path.join(pdir, cssname)).read()
            for name, body in re.findall(r'/\* (.*?) \*/\s*(@font-face \{.*?\})', txt, re.S):
                m = re.search(r'url\(\./files/(.*?)\)', body)
                if not m: continue
                fn = m.group(1)
                rest = fn[len(slug) + 1:] if fn.startswith(slug + '-') else fn
                sub = next((s for s in known if rest.startswith(s + '-')), None)
                if sub not in f['subsets']: continue
                body = re.sub(r"font-family: '.*?';", f"font-family: '{f['family']}';", body)
                body = re.sub(r'src: url\(\./files/(.*?\.woff2)\) format\(\'(.*?)\'\)(, url\(.*?\) format\(.*?\))?;',
                              lambda mm: f"src: url(../FONTS/{mm.group(1)}) format('{mm.group(2)}');", body)
                shutil.copy(os.path.join(pdir, 'files', fn if fn.endswith('.woff2') else fn), os.path.join(FD, fn))
                copied += 1
                out.append(f'/* {f["role"]} · {name} */\n{body}\n')
    open(os.path.join(CD, 'fonts.css'), 'w').write('\n'.join(out))
    print(f'{copied} font files → {FD} · fonts.css written')

if __name__ == '__main__':
    main()
